name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'

jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22

      - name: Test
        run: go test -cover -coverprofile=coverage.txt ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

  upload_coverage_main:
    if: github.ref == 'refs/heads/main'
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

      - name: Upload code coverage results to output directory
        run: mkdir -p .github/outputs && cp coverage.txt .github/outputs/coverage.txt

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

      - name: Download baseline coverage results
        run: |
          LAST_SUCCESSFUL_RUN_ID=$(gh run list --status=success --branch=main --workflow=CI --event=push --json=databaseId --limit=1 -q '.[] | .databaseId')
          if [ -z "$LAST_SUCCESSFUL_RUN_ID" ]; then
            echo "No previous successful runs found on the main branch."
            exit 1
          fi
          gh run download "$LAST_SUCCESSFUL_RUN_ID" --name=code-coverage --dir=.github/outputs || exit 1

      - uses: fgrosse/go-coverage-report@v1.0.1
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.txt"
